# Generated by Django 3.1.1 on 2020-10-01 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=40)),
                ('mobileno', models.CharField(blank=True, max_length=15)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('addresslane1', models.TextField(blank=True, max_length=100)),
                ('addresslane2', models.TextField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('postalzip', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
